source_directories:
  - /mnt/source/etc
  - /mnt/source/var
  - /mnt/source/usr/local
  - /mnt/source/opt
  - /mnt/source/root

exclude_patterns:
  - /var/cache/
  - /var/lock/
  - /var/run/
  - /var/tmp/
  - /var/local/
  - /var/opt/
  - /var/log/

exclude_if_present:
  - .nobackup

repositories:
  - path: /mnt/borg-repository/borg-backup/data
    label: local

retries: 3
retry_wait: 30

one_file_system: true

compression: lz4
archive_name_format: 'backup-data-{now:%Y-%m-%d-%H%M%S}'

keep_daily: 7
keep_weekly: 4
keep_monthly: 12
keep_yearly: 1

checks:
  - name: spot
    frequency: always
    count_tolerance_percentage: 10
    data_sample_percentage: 10
    data_tolerance_percentage: 0.5

  - name: repository
    frequency: 1 week

  - name: archives
    frequency: 1 month
    only_run_on:
      - weekend

  - name: data
    frequency: 2 months
    only_run_on:
      - weekday

  - name: extract
    frequency: 1 month
    only_run_on:
      - weekday

